# This playbook illustrates the creation of multiple volumes sequentially
---
- name: Creation of Multiple Volume
  hosts: localhost
  connection: local
  vars:
    array_ip: 'ip_address_of_the_array'
    user: 'your_username'
    password: 'your_password'
    verifycert: False
    vol_name: 'Volume_Module'
    cap_unit: 'GB'
  collections:
  - dellemc.powerstore
  tasks:
  - name: Create multiple volumes
    register: result_vol
    volume:
      array_ip: "{{array_ip}}"
      user: "{{user}}"
      password: "{{password}}"
      verifycert: "{{verifycert}}"
      vol_name: "{{vol_name +'_' }}{{item}}"
      size: 1
      cap_unit: "{{cap_unit}}"
      state: 'present'
# The loop will be executed for the number of elements in the list(created by the range).
    loop: "{{ range(1, 100+ 1,1) | list }}"
    
